---
- name: Update web servers
  hosts: ec2instances
  remote_user: ubuntu

  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest
