k3s_cluster:
  children:
    master:
      hosts:
        ec2-52-23-167-8.compute-1.amazonaws.com
    node:
      hosts:
        ec2-3-90-243-32.compute-1.amazonaws.com
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/TerraformTestKey2.pem"
