k3s_cluster:
  children:
    master:
      hosts:
        ec2-3-87-186-10.compute-1.amazonaws.com
    worker:
      hosts:
        ec2-184-73-67-44.compute-1.amazonaws.com
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/TerraformTestKey2.pem"
